apiVersion: v1
kind: Service
metadata:
  name: sql-server
  labels:
    app.kubernetes.io/name: sql-server
    app.kubernetes.io/component: database
spec:
  selector:
    app: sql-server
  ports:
  - port: 1433
    targetPort: 1433
 
