apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 448870721230.dkr.ecr.us-east-1.amazonaws.com/mysql_repo 
        ports:
        - containerPort: 3306
        env:
        - name: sql
        - name: MYSQL_ROOT_PASSWORD

